apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testjul16-0-test
  janus-idp.io/tekton: testjul16-0-test
  backstage.io/kubernetes-id: testjul16-0-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testjul16-0-test
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- rhoai/